services:
  discord-bot:
    build:
      context: ./discord_bot
      dockerfile: Dockerfile
    container_name: discord-bot
    restart: unless-stopped
    env_file:
      - ./discord_bot/app/.env
    volumes:
      - ./discord_bot/app:/app
